title: Jonathan Wilde
subtitle:
  Jonathan Wilde is a recent Tufts graduate heading soon to Facebook.
author: Jonathan Wilde
author_facebook: https://www.facebook.com/jonathan.wilde
author_twitter: https://twitter.com/hellojwilde
author_twitter_username: hellojwilde
author_instagram: https://instagram.com/hellojwilde
copyright_years: 2003 - 2015
public_url: http://jwilde.me
public_github_url: https://github.com/hellojwilde/hellojwilde.github.com