title: Jonathan Wilde
subtitle:
  Engineer thinking and tweeting about software, networks, and cities. Loves Caltrain more than Joe Biden loves Amtrak.
author: Jonathan Wilde
author_twitter: https://twitter.com/hellojwilde
author_twitter_username: hellojwilde
copyright_years: 2003 - 2020
public_url: http://jwilde.me
public_github_url: https://github.com/hellojwilde/hellojwilde.github.com